-- Mostrar demora(costo) de la ejecución

-- costo 3.75
/* codigo en cmd
EXPLAIN FORMAT = JSON SELECT A.CODIGO_DEL_PRODUCTO FROM tabla_de_productos A \G;
*/
SELECT A.CODIGO_DEL_PRODUCTO FROM tabla_de_productos A;

/*
costo 40037.77
codigo en cmd
EXPLAIN FORMAT = JSON SELECT A.CODIGO_DEL_PRODUCTO, C.CANTIDAD FROM tabla_de_productos A INNER JOIN items_facturas C  ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO; \G
*/
SELECT A.CODIGO_DEL_PRODUCTO, C.CANTIDAD FROM tabla_de_productos A INNER JOIN items_facturas C  ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO;


/*
costo 130084.99
explain format = json SELECT A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) AS ANIO, C.CANTIDAD FROM tabla_de_productos A INNER JOIN items_facturas C  ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO INNER JOIN facturas B ON C.NUMERO = B.NUMERO \G;
*/
SELECT A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) AS ANIO, C.CANTIDAD FROM tabla_de_productos A INNER JOIN items_facturas C  ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO INNER JOIN facturas B ON C.NUMERO = B.NUMERO;

/*
costo 130084.99
EXPLAIN FORMAT = JSON SELECT A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) AS ANIO, SUM(C.CANTIDAD) AS CANTIDAD FROM tabla_de_productos A INNER JOIN items_facturas C  ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO INNER JOIN facturas B ON C.NUMERO = B.NUMERO GROUP BY A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) ORDER BY A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) \G;
*/
SELECT A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) AS ANIO, SUM(C.CANTIDAD) AS CANTIDAD FROM tabla_de_productos A INNER JOIN items_facturas C  ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO INNER JOIN facturas B ON C.NUMERO = B.NUMERO GROUP BY A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) ORDER BY A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA);

-- Los costos aumentan por los JOINS usados, los GROUP BY O ORDER BY no afectan al costo